# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-15 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, verbose_name='Grupo de Investigación')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=320, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=30, verbose_name='Extensión o teléfono')),
                ('is_employee', models.BooleanField(verbose_name='¿Es empleado?')),
                ('expire_date', models.DateField(verbose_name='¿Cuándo termina el proyecto/postgrado?')),
                ('grupos', models.ManyToManyField(to='users.Group', verbose_name='Grupo de investigación')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Investigador Líder'),
        ),
    ]
